mirror-media/Lilith

packages/seinsights/lists/AboutUs.ts, packages/seinsights/lists/Event.ts, packages/seinsights/lists/EventBanner.ts, packages/seinsights/lists/HomepageBanner.ts, packages/seinsights/lists/JobBanner.ts, packages/seinsights/lists/Menubar.ts, packages/seinsights/lists/Post.ts, packages/seinsights/lists/ResourceBanner.ts, packages/seinsights/lists/Section.ts, packages/seinsights/lists/SpecialfeatureEditorChoice.ts, packages/seinsights/lists/SpecialfeatureList.ts, packages/seinsights/lists/index.ts, packages/seinsights/migrations/20220908020809_add_banner_editorchoice/migration.sql, packages/seinsights/migrations/20220908025954_/migration.sql, packages/seinsights/schema.graphql, packages/seinsights/schema.prisma
according to the [document](https://paper.dropbox.com/doc/keystone-CMS-list--Bou6rjdCdLk9k_t1riGqkW5DAg-35A1CzgkV0fbAuGO6kstX) adjust fields and lists
- new list: Specialfeature Editor choice, Job Banner, event Banner, resource Banner, home page Banner
- new field: storyType(post), section(SpecialfeatureList), topSpecialfeature(SpecialfeatureList)
- rm field: subtitle(post), isTop(event), banner(event)
=> feat: add new list(banner,editorchoice) and adjust field

packages/openrelationship/lists/PersonElection.ts, packages/openrelationship/lists/Politic.ts, packages/openrelationship/migrations/20221024042414_add_relationship_in_personelection/migration.sql, packages/openrelationship/schema.graphql, packages/openrelationship/schema.prisma
=> chore: merge staging to prod

packages/mesh/environment-variables.ts, packages/mesh/keystone.ts, packages/mirrormedia/environment-variables.ts, packages/openrelationship/environment-variables.ts, packages/readr/environment-variables.ts, packages/readr/keystone.ts, packages/seinsights/environment-variables.ts
遇到一堆 type error 導致 `yarn install` 失敗，
然後發現其實還有更多 type error ...，
總之先排除會導致 `yarn install` 失敗的 type error
=> fix(mesh/mirrormedia/openrelationship/readr/seinsights): type errors

.eslintrc.json, packages/editools/environment-variables.ts, packages/editools/keystone.ts, packages/editools/lists/FeedbackCounter.ts, packages/editools/lists/Karaoke.ts, packages/editools/lists/index.ts, packages/editools/migrations/20221109122959_add_feedback_counter_list/migration.sql, packages/editools/package.json, packages/editools/schema.graphql, packages/editools/schema.prisma, yarn.lock
* chore: update eslint rule, add `@typescript-eslint/ban-ts-comment` config
* chore(editools): update embed-code-generator to ^1.3.0
* fix(editools): type errors
* feat(editools): add `FeedbackCounter` list
=> feat(editools): add `FeedbackCounter` list

packages/mirrormedia/keystone.ts
Premium member mini app will be replaced by Weekly API Server(WAS) after WAS deployments.
=> refactor(mirrormedia): temporarily enable Premium member mini app

packages/core/package.json, packages/core/src/custom-fields/rich-text-editor/views/editor/image.tsx, packages/core/src/custom-fields/rich-text-editor/views/editor/shared/align-selector.tsx, packages/core/src/custom-fields/rich-text-editor/views/editor/shared/image-selector.tsx, packages/core/src/custom-fields/rich-text-editor/views/editor/shared/pagination.tsx, packages/core/src/custom-fields/rich-text-editor/views/editor/shared/post-selector.tsx, packages/core/src/custom-fields/rich-text-editor/views/editor/shared/search-box.tsx, packages/core/src/custom-fields/rich-text-editor/views/editor/shared/video-selector.tsx, packages/core/src/custom-fields/rich-text-editor/views/editor/slideshow.tsx, packages/readr/package.json, packages/seinsights/package.json
- update lilith-core package version to 1.2.1 only for Seinsights
- replace image, slideshow button with Vision's version
- remove unnecessary attributes using in Vision
- replace input with textarea to expand the height of the image caption
- change readr's lilith-core version to 1.2.0
- prevent using the latest special version
- change seinsights' lilith-core version to 1.2.1
=> Refactor(seinsights): update image and slideshow button

README.md, packages/editools/package.json, packages/mesh/package.json, packages/mirrormedia/package.json, packages/openrelationship/package.json, packages/readr/package.json
* Update package list and troubleshootings in README
* Fix installation issues on Windows
=> chore: fix installation issues on Windows

packages/editools/public/three/utils.js
This commit reverts f732f5acece7224282962b8f689f520462c67c06
=> revert(editools): uncomment draco loader

packages/editools/public/three/camera-helper/index.html, packages/editools/public/three/camera-helper/script.js
This patch
- updates wheel and keyboard scale factor
- adds camera helper operation manual
=> refactor(editools): update camera helper

packages/editools/package.json, yarn.lock
- 更新 edittools 裡 video picker 中的 `@readr-media/react-embed-code-generator` 版本。
=> refactor(edittools): update @readr-media/react-embed-code-generator to 2.1.5-alpha.nick.0

packages/readr/lists/Gallery.ts, packages/readr/migrations/20230319154249_fix_relation_between_gallery_and_author/migration.sql, packages/readr/schema.graphql, packages/readr/schema.prisma
* Fix relationship between `Gallery` and `Author` on writer field.  Gallery can have many Author on writer field.  Also, custom SQL query is added to migration script, so that existed records won't be lost.
=> refactor(readr): fix relation between Gallery and Author

packages/draft-renderer/.babelrc, packages/draft-renderer/package.json, packages/draft-renderer/src/website/readr/draft-renderer.tsx, yarn.lock
- add `.babelrc` install `inline-react-svg` to solve svg/png import problem
- bump up `@mirrormedia/lilith-draft-renderer` to version `1.1.0-alpha.2`
=> fix(draft-renderer): add `.babelrc` & install `inline-react-svg`

packages/mirrormedia/lists/Post.ts, packages/mirrormedia/migrations/20230328034606_add_manual_order_fields_in_post/migration.sql, packages/mirrormedia/schema.graphql, packages/mirrormedia/schema.prisma
- `relateds`
- `writers`
- `sections`
input order are recorded.
=> refactor(mirrormedia): record manual input order on certain fields

packages/draft-renderer/package.json, packages/draft-renderer/src/website/mirrormedia/block-renderers/divider-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/info-box-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx, packages/draft-renderer/src/website/mirrormedia/draft-renderer.tsx, packages/draft-renderer/src/website/mirrormedia/entity-decorators/annotation-decorator.tsx
1. 調整 `divider-block`顏色。
2. 調整 `order-list`樣式，解決數字列點破版問題。
3. 調整block之間的間距。
=> style(draft-renderer): add spacing between blocks, adjust style of several element

packages/draft-renderer/package.json, packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx, yarn.lock
點擊圖片時，將開啟圖片lightbox，並顯示更大的圖片。
當lightbox處於開啟狀態時，將暫時禁用瀏覽器的捲動功能。
當lightbox處於關閉狀態時，則啟用瀏覽器捲動功能。
=> feat(draft-renderer/image-block): click image block will show larger image lightbox

packages/draft-renderer/package.json, packages/draft-renderer/src/website/readr/block-renderers/background-image-block.tsx, packages/draft-renderer/src/website/readr/block-renderers/background-video-block.tsx
fix(draft-renderer): wrong css syntax issue
=> chore(draft-renderer): bump version

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/website/readr/selector/post-selector.tsx, packages/draft-renderer/package.json, packages/draft-renderer/src/website/readr/block-renderers/related-post-block.tsx, packages/readr/package.json, yarn.lock
- new UI for readr related post
- remove readr related post limit
=> refactor(draft-renderer/readr): remake related post

packages/draft-renderer/package.json, packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/info-box-block.tsx, packages/draft-renderer/src/website/mirrormedia/draft-renderer.tsx, packages/draft-renderer/src/website/mirrormedia/entity-decorators/annotation-decorator.tsx
1. 調整間距，將最後一個block的`margin-bottom`設為0
2. 新增premium版型的樣式
=> style(draft-renderer): add style for `contentLayout: premium`

packages/core/.views.babelrc.js, packages/core/Makefile, packages/core/package.json, packages/core/src/custom-fields/file/index.ts, packages/core/src/custom-fields/file/utils.ts, packages/core/src/custom-fields/file/views/Field.tsx, packages/core/src/custom-fields/file/views/index.tsx, packages/core/src/custom-fields/relationship/index.ts, packages/core/src/custom-fields/relationship/views/RelationshipSelect.tsx, packages/core/src/custom-fields/relationship/views/cards/InlineCreate.tsx, packages/core/src/custom-fields/relationship/views/cards/InlineEdit.tsx, packages/core/src/custom-fields/relationship/views/cards/index.tsx, packages/core/src/custom-fields/relationship/views/cards/useItemState.tsx, packages/core/src/custom-fields/relationship/views/index.tsx, packages/core/src/custom-fields/rich-text-editor/index.ts, packages/core/src/custom-fields/timestamp/index.ts, packages/core/src/custom-fields/timestamp/views/__tests__/index.tsx, packages/core/src/custom-fields/timestamp/views/__tests__/utils.tsx, packages/core/src/custom-fields/timestamp/views/index.tsx, packages/core/src/custom-fields/timestamp/views/utils.ts, packages/core/src/custom-fields/utils/graphql-errors.ts, packages/core/src/custom-fields/utils/integer/utils.ts, packages/core/src/custom-fields/utils/non-null-graphql.ts, packages/core/src/custom-fields/utils/text/utils.ts, packages/core/src/index.ts
This reverts commits
- 0c931e57ec3a3ee1a116565d73bf3c9051bd677d
- 168ba0417c1e4da12a33f9118ae402c1f39b60cb
- 6bf2840b6f4dfd0a87438c0928bc9c29ec4f0eb6
- eed4c4d85645f7ba76e8ea54d9ae1edd0268a972
因為有更改 lilith-core 的需求，所以將 main branch 的 packages/core 降回 1.2.8 的版本。
lilith-core@2.0.0 的 source code 則被 merge 進 `latest-k6` branch。
=> revert(core): rollback to @1.2.8 code base

packages/mirrormedia/lists/Post.ts
- 更新判斷「文章是否為會員文章」的邏輯：採用 `isMember` 欄位，而非看文章的 `category.isMemberOnly`
=> refactor(mirrormedia): change member post business logic

packages/mirrormedia/lists/Post.ts, packages/mirrormedia/lists/Video.ts, packages/mirrormedia/migrations/20230707020537_add_relationship_between_videos_and_posts/migration.sql, packages/mirrormedia/schema.graphql, packages/mirrormedia/schema.prisma
分別在
Video 新增欄位如下
相關文章
相關文章手動排序結果
Post 新增欄位如下
相關影片
相關影片手動排序結果
=> feat(mirrormedia): add related_videos, related_posts in Post.ts and Video.ts

packages/editools/lists/Theatre.ts, packages/editools/package.json, yarn.lock
- 調整 `lists/Theatre.ts` 內 embed-code 產生設定。
- 更新 `@readr-media/react-embed-code-generator` 版本至 `2.4.0-alpha.1`。
=> feat(editools/theatre): add embedCode settings

packages/mirrormedia/config.ts, packages/mirrormedia/lists/Image.ts, packages/mirrormedia/schema.graphql
* Access images by Cloud CDN instead of Google API
* Support multiple size for webP
=> fix(mirrormedia): adjust the Image list

packages/editools/package.json, yarn.lock
- `embed-code-generator` 版本更新至 `2.4.3-alpha.2`。
-  調整 `dropping-text` 背景顏色為 `#ffffff`。
=> chore(editools): update `ecg` version

packages/mirrormedia/express-mini-apps/preview/app.js, packages/mirrormedia/keystone.ts, packages/mirrormedia/lists/Post.ts
* Add `/_next/` to preview route
* Fix type related issues in `Post` list
* Fix `Post` list ACL issue
* Remove unused codes
=> refactor(mirrormedia): add _next to preview route

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/website/mirrormedia/selector/audio-selector.tsx, packages/draft-editor/src/website/mirrormedia/selector/image-selector.tsx, packages/draft-editor/src/website/mirrormedia/selector/post-selector.tsx, packages/draft-editor/src/website/mirrormedia/selector/video-selector.tsx, packages/draft-editor/src/website/readr/selector/audio-selector.tsx, packages/draft-editor/src/website/readr/selector/image-selector.tsx, packages/draft-editor/src/website/readr/selector/post-selector.tsx, packages/draft-editor/src/website/readr/selector/video-selector.tsx, packages/mirrormedia/package.json, packages/mirrormedia/yarn.lock, packages/readr/package.json
Involved pacakge 
- mirrormedia
- readr
=> refactor(draft-editor): gql order by id

packages/mirrormedia/environment-variables.ts, packages/mirrormedia/express-mini-apps/preview/app.js, packages/mirrormedia/keystone.ts, packages/mirrormedia/lists/Post.ts
* Add `PREVIEW_SERVER_PATH`
* Update preview server routes
=> refactor(mirrormedia): update preview server routes

packages/mirrormedia/lists/EditorChoice.ts, packages/mirrormedia/lists/Image.ts
- feat: update editor permission to delete photo
- feat: sort relationship field in EditorChoice list
=> feat(mirrormedia): adjust the permission and ui view

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/draft-js/buttons/link.tsx, packages/draft-editor/src/draft-js/util.js, packages/mirrormedia/package.json, yarn.lock
- fix select first block issue
- link editable
=> refactor(draft-editor): update link button

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/website/mirrormedia/draft-editor.tsx, packages/draft-editor/src/website/mirrormedia/shared-style/index.ts, packages/mirrormedia/package.json
- align block margin bottom
- add letter-spacing for whole editor
=> style(draft-editor): update mirrormedia style

packages/draft-renderer/package.json, packages/draft-renderer/src/website/mirrormedia/block-renderer-fn.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/audio-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/embedded-code-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/info-box-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/video-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/youtube-block.tsx, packages/draft-renderer/src/website/mirrormedia/draft-renderer.tsx, packages/draft-renderer/src/website/mirrormedia/entity-decorator.tsx, packages/draft-renderer/src/website/mirrormedia/entity-decorators/annotation-decorator.tsx, packages/draft-renderer/src/website/mirrormedia/entity-decorators/link-decorator.tsx, packages/draft-renderer/src/website/mirrormedia/types/index.ts
1. 新增types 資料夾，並新增type `ContentLayout`，並用於需要的元件/函式中，以解決typescript相關錯誤。
2. 使用image 中的imageFile `width` 與 `height`，以計算 `aspect-ratio` 。
3. draft-renderer 升版至 `1.3.0-alpha.15`
=> refactor(DR): add type `ContentLayout`, add style

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/draft-js/buttons/selector/image-selector.tsx, packages/draft-editor/src/website/mirrormedia/selector/image-selector.tsx, packages/mirrormedia/package.json, yarn.lock
1. 調整draft-editor中image selector的gql query，新增抓取imageFile width、height兩個值，該值將用於draft-renderer中計算aspect-ratio使用
2. 調應套件升版
=> feat(DE): update gql query in image selector, upgrade package

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/draft-js/buttons/audio.tsx, packages/draft-editor/src/draft-js/draft-converter/atomic-block-processor.js, packages/draft-editor/src/draft-js/draft-converter/entities.js, packages/draft-editor/src/website/mirrormedia/block-renderer-fn.tsx, packages/draft-editor/src/website/mirrormedia/selector/audio-selector.tsx, packages/draft-renderer/package.json, packages/draft-renderer/src/website/mirrormedia/block-renderer-fn.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/amp/amp-audio-block-v2.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/audio-block.tsx, packages/draft-renderer/src/website/mirrormedia/block-renderers/index.ts, packages/mirrormedia/package.json, yarn.lock
改動同[此PR](https://github.com/mirror-media/Lilith/pull/589)，除了 audioSrc 之前已經先添加到 audioSelector
=> refactor(DR, DE): mirrormedia use audio-v2 version

packages/mirrormedia/lists/Magazine.ts, packages/mirrormedia/schema.graphql
=> refactor(mirrormedia): drop pdfSrc in Magazine list

.eslintrc.json, .gitignore, babel.config.js, package.json, packages/core/CHANGELOG.md, packages/core/Makefile, packages/core/package.json, packages/core/src/custom-fields/rich-text-editor/index.ts, packages/core/src/custom-fields/rich-text-editor/views/mirrormedia/index.tsx, packages/core/src/custom-fields/rich-text-editor/views/readr/index.tsx, packages/core/src/index.ts, packages/core/src/utils/accessControl.ts, packages/core/src/utils/manual-order-relationship.ts, packages/core/src/utils/trackingHandler.ts, packages/core/tsconfig.json, yarn.lock
* upgrade prettier package to 2
* upgrade babel target node version to 16
* fix type issues in richTextEditor
* fix type issues in trackingHandler util
* fix type issues in manual-order-relationship util
* fix type issues in accessControl util
* add type files to build process
* bump version to 2.1.1
=> refactor(lilith-core): fix type issues

packages/core/CHANGELOG.md, packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/website/mirrormedia/block-renderer/embedded-code-block.tsx
* fix(draft-editor): CLS issue in EmbeddedCodeEditorBlock of MirrorMedia
* chore(draft-editor): bump version to 1.2.0
* chore(lilith-core): bump version to 2.2.0
=> fix(draft-editor): CLS issue in EmbeddedCodeEditorBlock of MM

packages/mirrormedia/package.json
* https://github.com/mirror-media/Lilith/pull/677
=> chore(mirrormedia): upgrade lilith-core to 2.2.0

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/website/mirrormedia/selector/image-selector.tsx, packages/mirrormedia/package.json
調整image-selector中單次搜尋的數量，從6個提升至18個。
=> feat(DR/image-selector): adjust the amount of result when search images

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/draft-js/buttons/selector/video-selector.tsx, packages/draft-editor/src/draft-js/buttons/video.tsx, packages/draft-editor/src/website/mirrormedia/selector/search-box.tsx, packages/draft-editor/src/website/mirrormedia/selector/video-selector.tsx, packages/draft-renderer/package.json, packages/draft-renderer/src/website/mirrormedia/block-renderers/video-block.tsx, packages/mirrormedia/package.json, yarn.lock
新增週刊 cms video button desc 欄位
```
{
video, // 原本的 video
desc, // 本次新增的欄位
}
```
video type 若 desc 的值為 truthy 就顯示，比照 youtube-block 的 style
須更新週刊3.0 draft-renderer 版本， @mirrormedia/lilith-draft-renderer@1.3.2
=> refactor(DR/mm, DE/mm): video button add desc prop

packages/mirrormedia/lists/External.ts, packages/mirrormedia/lists/Tag.ts, packages/mirrormedia/migrations/20240402093957_add_external_tag_column/migration.sql, packages/mirrormedia/schema.prisma
新增tags與related欄位至外部文章(External)當中，並在標籤(Tag)中新增外部文章標籤欄位。
=> feat(mm): extend external with tags and related attributes

packages/mesh/lists/story.ts, packages/mesh/migrations/20240425081636_story_api_data/migration.sql, packages/mesh/migrations/20240426021317_add_trim_data/migration.sql, packages/mesh/schema.graphql, packages/mesh/schema.prisma
為了讓mesh能儲存apiData，在story頁面新增apiData欄位。
由於有更動到schema，故有migration.sql檔案。
=> feat(mesh): add apiData to story

package.json, packages/mirrordaily/keystone.ts, packages/mirrordaily/lists/Category.ts, packages/mirrordaily/lists/Section.ts, packages/mirrordaily/migrations/20240606085316_update_section_color/migration.sql, packages/mirrordaily/package.json, packages/mirrordaily/schema.graphql, packages/mirrordaily/schema.prisma
* Upgrade `"@mirrormedia/lilith-core` package to `2.4.0`
* Update Section `color field
* Add `mirrordaily` to monorepo packages
=> refactor(mirrordaily): update section color field

packages/mirrordaily/migrations/20240724083125_add_editor_choices_column_hero_image_remove_published_date_column/migration.sql, packages/mirrordaily/migrations/20240724161735_add&remove_game&editorchoice_list/migration.sql
已在本地端對 Cloud 上的 DB Server 執行相關[指令](https://www.prisma.io/docs/orm/reference/prisma-cli-reference#migrate-resolve)，該 PR merge 後，即可重跑 migration
=> fix(daily): migration failure

packages/mirrordaily/lists/Topic.ts, packages/mirrordaily/lists/Video.ts, packages/mirrordaily/migrations/20240820110742_update_video_list/migration.sql, packages/mirrordaily/migrations/20240821022742_add_hero_video_to_topic_list/migration.sql, packages/mirrordaily/schema.graphql, packages/mirrordaily/schema.prisma
* 調整 Video List
* 增加上傳者欄位 (`uploader`, `uploaderEmail`)
* 增加是否為短影音欄位 (`isShorts`)
* 調整敘述欄位為純文字
* 移除 `urlOriginal` 欄位
* 調整預設清單欄位顯示
* 調整 Topic List
* 增加和影片的關聯 (`heroVideo` | `首圖影片（Leading Video）`)
---
- https://app.asana.com/0/0/1207977476935248
- https://app.asana.com/0/0/1208008918991315
- https://app.asana.com/0/0/1208098060027463
- https://app.asana.com/0/0/1207963548143188
=> feat(mirrordaily): update Video and Topic list

packages/mirrordaily/lists/Image.ts, packages/mirrordaily/migrations/20240826111734_remove_file_field_from_image_list/migration.sql, packages/mirrordaily/schema.graphql, packages/mirrordaily/schema.prisma
* 移除 Image List 中的 `file` field
* Image 檔案相關的邏輯都轉移到 `imageFile` 上了，應移除 `file` 欄位，避免產生混淆
=> refactor(mirrordaily): remove file field from image list

packages/mirrordaily/admin/components/button.tsx, packages/mirrordaily/admin/components/editor-step.tsx, packages/mirrordaily/admin/components/item.tsx, packages/mirrordaily/admin/components/modal.tsx, packages/mirrordaily/admin/components/submission-button-and-modal.tsx, packages/mirrordaily/admin/redux/features/multi-images/selector.ts, packages/mirrordaily/admin/redux/features/multi-images/slice.ts
=> feat(mirrordaily): add multiple images deletion

packages/mirrormedia/admin/components/button.tsx, packages/mirrormedia/admin/components/custom-navigation.tsx, packages/mirrormedia/admin/components/editor-step.tsx, packages/mirrormedia/admin/components/hidden-input.tsx, packages/mirrormedia/admin/components/initial-step.tsx, packages/mirrormedia/admin/components/item.tsx, packages/mirrormedia/admin/components/main-container.tsx, packages/mirrormedia/admin/components/modal.tsx, packages/mirrormedia/admin/components/submission-button-and-modal.tsx, packages/mirrormedia/admin/config.ts, packages/mirrormedia/admin/pages/multi-images.tsx, packages/mirrormedia/admin/redux/features/multi-images/selector.ts, packages/mirrormedia/admin/redux/features/multi-images/slice.ts, packages/mirrormedia/admin/redux/hooks.ts, packages/mirrormedia/admin/redux/listener-middleware.ts, packages/mirrormedia/admin/redux/store.ts, packages/mirrormedia/admin/utils/index.ts, packages/mirrormedia/package.json
* 同 https://github.com/mirror-media/Lilith/pull/750 https://github.com/mirror-media/Lilith/pull/751
* 增加多張圖片上傳頁 (`/multi-images`)
---
- https://app.asana.com/0/0/1208220951749666
=> feat(mirrormedia): add multiple images upload page

packages/mesh/lists/index.ts, packages/mesh/lists/invalid_name.ts, packages/mesh/lists/publisher.ts, packages/mesh/migrations/20241028062848_add_invalid_name_and_publisher_active/migration.sql, packages/mesh/schema.graphql, packages/mesh/schema.prisma
新增兩個資料
1. invalid_name list: 提供禁止使用的名稱欄位。
2. active: publisher list新增active, 用以判斷該媒體是否停用。
由於有資料庫欄位更動，故有提供migrations檔案。
=> feat(mesh): add invalid_name list and add active field into publisher

packages/mesh/lists/index.ts, packages/mesh/lists/report_reason.ts, packages/mesh/lists/report_record.ts, packages/mesh/migrations/20250103061054_add_report_reason_and_record_list/migration.sql, packages/mesh/schema.graphql, packages/mesh/schema.prisma
=> feat:add report reason & record list

packages/mesh/lists/tag.ts, packages/mesh/migrations/20250107022344_modify_tag_name_unique_attribute/migration.sql, packages/mesh/schema.graphql, packages/mesh/schema.prisma
原先的Tag實作並沒有成功的將name設定為unique，這邊修改此段程式碼使Tag.name為unique。
=> refactor: modify tag.name unique attribute

packages/mesh/lists/member.ts, packages/mesh/lists/publisher.ts, packages/mesh/migrations/20250123032440_add_exclude_publisher/migration.sql, packages/mesh/schema.graphql, packages/mesh/schema.prisma
在會員list當中新增排除媒體欄位，此欄位用途為排除不想被推薦的媒體列表
=> feat(mesh): add exclude publisher field to member

packages/draft-renderer/Makefile, packages/draft-renderer/README.md, packages/draft-renderer/package.json
* 更新 Makefile
* 修正 README 的錯誤
* 更新 peer dependecies 套件的版本設定
=> chore(draft-renderer): bump version to 1.4.0

packages/mesh/lists/statement.ts, packages/mesh/migrations/20250306070332_modify_statement_type/migration.sql, packages/mesh/schema.graphql, packages/mesh/schema.prisma
=> refactor(mesh): rename the type of statement

packages/draft-editor/package.json, packages/draft-editor/src/draft-js/buttons/selector/video-selector.tsx, packages/draft-editor/src/website/mirrormedia/draft-editor.tsx, packages/draft-editor/src/website/readr/block-renderer-fn.tsx, packages/draft-editor/src/website/readr/draft-editor.tsx, packages/draft-editor/src/website/readr/selector/align-selector.tsx, packages/draft-editor/src/website/readr/selector/audio-selector.tsx, packages/draft-editor/src/website/readr/selector/image-selector.tsx, packages/draft-editor/src/website/readr/selector/pagination.tsx, packages/draft-editor/src/website/readr/selector/post-selector.tsx, packages/draft-editor/src/website/readr/selector/search-box.tsx, packages/draft-editor/src/website/readr/selector/video-selector.tsx
* 修正 `website/readr` 底下（`website/readr/block-renderer` 除外）與 type 相關的問題
=> chore(draft-editor): bump version to 2.3.0

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/custom-fields/rich-text-editor/index.ts, packages/core/src/custom-fields/rich-text-editor/views/mirrordaily/index.tsx, packages/core/src/custom-fields/rich-text-editor/views/mirrormedia/index.tsx, packages/core/src/custom-fields/rich-text-editor/views/readr/index.tsx, packages/core/src/custom-fields/rich-text-editor/views/utils.tsx
* 將產生 RichTextEditor view 的建立邏輯統一管理
* 增加 mirrordaily 的 view 至 RichTextEditor
=> chore(core): bump version to 2.6.0

packages/mirrordaily/admin/pages/custom-post-creation/index.tsx, packages/mirrordaily/lists/External.ts, packages/mirrordaily/lists/Post.ts, packages/mirrordaily/migrations/20250315140809_hide_slug_field_of_post_and_external_list/migration.sql, packages/mirrordaily/schema.graphql, packages/mirrordaily/schema.prisma
* post 和 external list 的 slug field 不再是 index，使用到該欄位作為 unique search 或者排序的操作需要調整
=> refactor(daily): hide slug field of post and external list

packages/mirrordaily/admin/pages/custom-post-creation/index.tsx, packages/mirrordaily/lists/User.ts, packages/mirrordaily/migrations/20250315141804_add_sections_field_to_user_list/migration.sql, packages/mirrordaily/schema.graphql, packages/mirrordaily/schema.prisma
* 增加 User 與 Section 的關聯
* 使用者使用客製化文章建立 UI 時，自動帶入使用者關聯的 Section 資訊
=> feat(daily): add user's sections to section field in CustomPostCreation UI

packages/mirrordaily/lists/User.ts
* 調整 User list 的權限，解決使用者在 CustomPostCreation UI 時，無法正確帶入其 Section 的問題
* 因為開放 editor 和 contributor 可以存取 User list，額外增加以下設定：
* 在 listing 的部份，admin 維持拿到全部項目，moderator 可以拿到 moderator, editor 和 contributor, 其他 role 只能拿到自己 
* 限制 name, email, password 和 role 欄位僅現 admin 可以更新
* 針對 sections 欄位，admin 可以更新所有 role 的資料，moderator 可以更新自己和 editor, contributor role 的資料，其他 role 則無法更新任何資料
=> refactor(daily): update User list ACL

packages/mirrordaily/admin/pages/custom-post-creation/index.tsx, packages/mirrordaily/lists/Post.ts
---
- https://app.asana.com/0/0/1209770511751522
=> refactor(daily): allow heroImage and relateds field in CustomPostCreation UI

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/index.ts, packages/core/src/utils/invalidate-cache-after-operation.ts
* utils 增加 `invalidateCacheAfterOperation` function
=> chore(core): bump version to 3.0.0

packages/core/CHANGELOG.md, packages/core/package.json
=> chore(core): bump version to 3.0.1

packages/readr/environment-variables.ts, packages/readr/lists/Post.ts, packages/readr/package.json, yarn.lock
---
- https://app.asana.com/0/0/1209783745337728
=> feat(readr): add cache invalidate on post list

packages/mirrormedia/Dockerfile, packages/mirrormedia/environment-variables.ts, packages/mirrormedia/lists/Post.ts, packages/mirrormedia/package.json, yarn.lock
* post list 增加 cache invalidation 處理
* 將 context.query 的使用調整為 context.prisma，以便免重複 trigger
* Node.js 升版至 18
---
- https://app.asana.com/0/0/1209783745337727
=> feat(mirrormedia): add cache invalidation on post list

packages/core/package.json, packages/draft-editor/package.json, packages/draft-editor/src/draft-js/buttons/youtube.tsx, packages/mirrordaily/package.json, packages/mirrormedia/package.json, yarn.lock
Support youtube url input by get youtube id before save it to draft.js block.
=> refactor(draft-editor): youtube button support url format

packages/mirrordaily/admin/pages/custom-post-creation/index.tsx, packages/mirrordaily/lists/Contact.ts, packages/mirrordaily/lists/User.ts, packages/mirrordaily/migrations/20250409024531_move_sections_from_user_to_contact/migration.sql, packages/mirrordaily/schema.graphql, packages/mirrordaily/schema.prisma
* CustomPostCreation UI 增加「首圖圖說」欄位
* User list 增加和 Contact list 的關聯
* User list 底下的 sections 搬移到 Contact list 底下
---
- https://app.asana.com/0/0/1209911531723636
- https://app.asana.com/0/0/1209911534804687
=> refactor(daily): move sections from User to Contact

packages/mirrordaily/lists/Audio.ts, packages/mirrordaily/lists/Category.ts, packages/mirrordaily/lists/Contact.ts, packages/mirrordaily/lists/EditorChoice.ts, packages/mirrordaily/lists/Event.ts, packages/mirrordaily/lists/External.ts, packages/mirrordaily/lists/Game.ts, packages/mirrordaily/lists/Group.ts, packages/mirrordaily/lists/Header.ts, packages/mirrordaily/lists/Partner.ts, packages/mirrordaily/lists/PopularTag.ts, packages/mirrordaily/lists/Post.ts, packages/mirrordaily/lists/Section.ts, packages/mirrordaily/lists/Tag.ts, packages/mirrordaily/lists/Topic.ts, packages/mirrordaily/lists/User.ts, packages/mirrordaily/lists/Video.ts, packages/mirrordaily/lists/Warning.ts
---
- https://app.asana.com/0/0/1209938771401029
=> refactor(daily): update whole CMS ACL configuration

packages/mirrordaily/admin/utils/use-create-item.ts, packages/mirrordaily/lists/Contact.ts, packages/mirrordaily/lists/Post.ts, packages/mirrordaily/lists/views/post/contact-relationship/CreateItemDrawer.tsx, packages/mirrordaily/lists/views/post/contact-relationship/RelationshipSelect.tsx, packages/mirrordaily/lists/views/post/contact-relationship/index.tsx, packages/mirrordaily/lists/views/post/contact-relationship/util.ts, packages/mirrordaily/migrations/20250415075645_add_role_to_contact_list/migration.sql, packages/mirrordaily/schema.graphql, packages/mirrordaily/schema.prisma, packages/mirrordaily/type.ts
* 調整在 Post list 中，關聯到 Contact list 的 field 顯示所使用的 view，使其滿足以下行為：
* 在列舉時，僅顯示符合條件 (`role`) 的 item
* 在建立 item 時，自動帶入 `role` 的資訊，使 item 建立後，能夠被正確得列舉到
---
- https://app.asana.com/0/0/1209979143683959
=> refactor(daily): update views of field that related to Contact list

packages/mirrordaily/lists/Post.ts
---
- https://app.asana.com/0/0/1209977583666170
=> fix(daily): error in lockBy handle

packages/core/src/utils/manual-order-relationship.ts
- 新增檢查機制，確保所有關聯項目都被正確記錄在排序中
- 當發現有缺失的關聯項目時，自動將其添加到排序列表的最後
- 保留原有的手動排序順序，只補充缺失項目
我去渡假了，如果 reviewer 覺得哪裡需要改（像我覺得在 hook 裡面使用 prisma 就很不優雅），就交給你接下去了 orz
=> refactor: ensure manual order relationship completeness by adding missing items

packages/draft-editor/src/draft-js/draft-converter/index.js, packages/draft-editor/src/website/readr/draft-editor.tsx
add superscript and subscript buttons
=> feat(draft-editor): add superscript and subscript buttons

packages/mirrordaily/utils/video-duration.ts
原本只考慮 error，應該要考慮 file not exists
=> fix(daily): retry download from gcs if file not exists

packages/mirrordaily/package.json, packages/mirrordaily/utils/video-duration.ts, yarn.lock
=> fix(daily): download video from source

packages/mirrordaily/Dockerfile, packages/mirrordaily/utils/background-video-processing.ts, packages/mirrordaily/utils/video-duration.ts
- missing install ffmpeg
- set fileDuration default as empty string
=> fix: calc video duration
