packages/editools/lists/QAItem.ts
packages/editools/lists/QAList.ts
packages/editools/lists/index.ts
packages/editools/migrations/20220921092054_add_qa_list_and_qa_item/migration.sql
packages/editools/schema.graphql
packages/editools/schema.prisma

- add `lists/QAList.ts`
- add `lists/QAItem.ts`
- 從 `lists/Form.ts` 中抽出與 Q&A 有關的欄位（只留必要的欄位）
- 在 QAList 中，透過 virtual field 產生 embed code
- 刪除 Form.ts 中與 Q&A 有關的欄位與邏輯。
- 目前的 `@readr-media/react-embed-code-generator` 產生的 `@readr-media/react-qa-list` 不支援 `font-color` 按鈕，需要找時間更新 `@readr-media/react-qa-list` 套件。

feat(editools): add QAList and QAItem

---

cloudbuild.yaml
packages/editools/Dockerfile
packages/mirrormedia/Dockerfile
packages/seinsights/Dockerfile
packages/vision/Dockerfile

- 將 docker build 改為 gcloud builds submit 後，gcloud builds submit 會使用 Kanoki cache 來 cache docker image layer。
[文件說明](https://cloud.google.com/build/docs/optimize-builds/kaniko-cache)：
> if you run builds using the gcloud builds submit --tag [IMAGE] command, you can enable Kaniko cache by setting the property builds/use_kaniko to True as shown below: `gcloud config set builds/use_kaniko True`
- 在 yarn install 前一個 step，只 copy 需要的檔案，當 copy 的檔案沒有變動時，`yarn install` step 就會使用 cache 的版本。

chore: update cloudbuild.yaml and Dockerfile to speed up build time

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/index.ts
packages/core/src/utils/manual-order-relationship.ts
packages/seinsights/lists/SpecialfeatureList.ts
packages/seinsights/migrations/20221226071620_add_manual_order_of_specialfeatures/migration.sql
packages/seinsights/package.json
packages/seinsights/schema.graphql
packages/seinsights/schema.prisma
yarn.lock

For relationship fields, KeystoneJS won't take input order into account. Therefore, if we want to remember the input order, we need to do it by ourselves.
This commit adds `manualOrderOfSpecialFeatures` field, which is used to record the input order of `specialfeatures` field.
We monitor the input order in `resolveInput` hook. If the order changes, we adjust `manualOrderOfSpecialFeatures` field correspondingly.
You can see the different orders in `SpecialFeatures` and `SpecialFeatures 手動排序結果` fields.

feat: update SpecialfeatureList.ts. Record the user input order of relationship `specialfeatures` field

---

cloudbuild.yaml

The build fails unexpectedly due to Kaniko cache using too much memory. Out of memory will make build containers be killed by system. This seems a known issue.
Before this issue is fixed, we change the cache mechanism by using `docker --cache-from` instead.

chore: disable kaniko cache. Use docker --cache-from mechanism instead

---

packages/seinsights/keystone.ts
packages/seinsights/lists/Post.ts
packages/seinsights/lists/Specialfeature.ts
packages/seinsights/schema.graphql

- add preview server and proxy article page to preview server
將要到 `/article/:id` 的 requests proxy 到 preview server，讓 preview server 產生 article page ，回傳 article page html 給 CMS server，CMS server 再將 preview server 產生的 article page html 回傳給瀏覽器。瀏覽器進而得以呈現文章頁。
但因為產生 `/article/:id` article page 的 preview server 是由「使用 nextjs 的 seinsights-next」 部署產生，article page 在瀏覽器 render 時，會需要 requests `/_next/*` 底下的 bundle js 和 server js 。然而，「lilith-seinsights 也是透過 nextjs 產生的服務」，所以 lilith-seinsights 本身也會提供 `/_next/*` routes，導致出現重複的 routes，article page 因而無法正常 render。
此 PR 透過 request Referer header `req.header('referer')` 來幫忙判斷現在進來 `/_next/*` 的 requests 是 article page 發起的 還是 CMS web pages 所發起的 requests。如果是 Referer 的網址是 `/article/:id` 結尾，代表是 article page，就將 requests proxy 到 preview server，反之，則進到 CMS server 提供的 …

feat(seinsights): enable article preview page

---

packages/mirrormedia/lists/Category.ts
packages/mirrormedia/lists/Post.ts
packages/mirrormedia/migrations/20230117062209_category_add_is_member_only_field/migration.sql
packages/mirrormedia/schema.graphql
packages/mirrormedia/schema.prisma
packages/mirrormedia/utils/gcp-logging.js

https://app.asana.com/0/1181156545719626/1203646042182610/f
1. add `trimmedContet` field: 保留 `content` 前 5 個 blocks（不包含空白換行）。
2. update `content` field: 加入「是否為會員文章的判斷」，如果使用者不是 Premium member，且文章是會員文章，則 return `null`
前端在 query 時，可以 `trimmedContent` 和 `content` 一起 query，如果 `content` 不是 `null`，代表使用者可以閱讀該篇文章（文章可能是一般文章或是會員文章）。如果 `content` 是 `null`，則可以使用 `trimmedContent` 來呈現部分文章，並且提示使用者需要註冊成為 Premium 會員才能閱讀。

feat(mirrormedia): add `trimmedContent` field and restrict `content` access 

---

packages/editools/lists/InlineIndex.ts

修復 InlineIndex 的長方形沒有對齊的問題，請見下圖。

style(editools): update InlineIndex css

---

packages/readr/lists/Feature.ts
packages/readr/migrations/20230301052941_fix_relationship_between_feature_and_post/migration.sql
packages/readr/schema.graphql
packages/readr/schema.prisma

* Follow conclusions of https://github.com/mirror-media/Lilith/pull/224, set relationship between `Feature` and `Post` to be one to one

refactor(readr): fix relationship between feature and post

---

packages/editools/http2-proxy-server.js
packages/editools/package.json
packages/editools/run.sh
yarn.lock

This PR adds a http/2 reverse proxy server, which is on behalf of the Keystone server.
The reason we need a http/2 server is because Cloud Run does limit request size under 32 MB if the request is not using http/2 protocol. See [document](https://cloud.google.com/run/quotas) for more info.
But, Keystone does not support http/2 protocol. We only have to create the reverse proxy server for it.

chore(editools): update run.sh. Enable http2 proxy

---

.gitignore
packages/core/package.json
packages/draft-editor/package.json
packages/draft-editor/src/draft-js/buttons/audio.tsx
packages/draft-editor/src/draft-js/buttons/selector/audio-selector.tsx
packages/draft-editor/src/draft-js/buttons/video.tsx
packages/draft-editor/src/website/mirrormedia/block-renderer-fn.tsx
packages/draft-editor/src/website/mirrormedia/draft-editor.tsx
packages/draft-editor/src/website/mirrormedia/selector/audio-selector.tsx
packages/draft-editor/src/website/mirrormedia/selector/image-selector.tsx
packages/draft-editor/src/website/mirrormedia/selector/video-selector.tsx
packages/draft-editor/src/website/readr/block-renderer-fn.tsx
packages/draft-editor/src/website/readr/draft-editor.tsx
packages/draft-editor/src/website/readr/selector/audio-selector.tsx
packages/draft-editor/src/website/readr/selector/image-selector.tsx
packages/draft-editor/src/website/readr/selector/video-selector.tsx
packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderer-fn.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/audio-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/index.ts
packages/draft-renderer/src/website/mirrormedia/block-renderers/video-block.tsx
packages/draft-renderer/src/website/readr/block-renderer-fn.tsx
packages/draft-renderer/src/website/readr/block-renderers/audio-block.tsx
packages/draft-renderer/src/website/readr/block-renderers/index.ts
packages/draft-renderer/src/website/readr/block-renderers/video-block.tsx
packages/editools/package.json
packages/mirrormedia/package.json
packages/readr/package.json
yarn.lock

- add video and audio buttons for both mirrormedia and readr websites in draft-editor
- add video and audio block renderers for both mirrormedia and readr websites in draft-renderer

feat(draft-js): add video and audio buttons

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx

使用`useMemo`，以避免slideshow元件所使用的`CustomImage`，不斷重新re-render
由於在拖曳的過程中，state `dragDistance`會不斷改變，並導致該元件re-render。而該元件re-render時，也會導致其中所使用的元件`CustomImage`也被re-render，並會造成該`CustomImage`的useEffect重跑一次，導致會對已經取得圖片url重新發request，產生不必要的request。
該PR則使用了useMemo，避免`CustomImage`會在slideshow re-render時一併re-render

refactor(draft-renderer/slideshow): add useMemo to prevent unneed re-render

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/readr/block-renderers/embedded-code-block.tsx
yarn.lock

原本在 useEffect 才把全部 embed code append 到 DOM 上面的做法會導致 non-script 的 tags (包含 html tag 和 style tag) 會在 useEffect 才被 append 到 dom 上面造成 embed code 的內容憑空出現把內容往下擠的跳動。
透過將 non-script tags 從 embed code 中分離出來塞進 dangerouslySetInnerHtml 之中不僅可以提早 non-script tags render 的時間，更可以讓 SSR 產生的 HTML 就直接包含這些 non-script tags，達到優化使用者體驗的效果。
`dangerouslySetInnerHtml` 雖然不會讓 script tag 在被 set 完之後被執行(因為底層就是使用`setInnerHtml`)，但仍然會存在在產生出來的 HTML 之中，在 CSR 的情況下不會有問題，但在 SSR 之下就會造成 server side 產生的 HTML 上含有 embed code 的 script tags，當 browser 解析 HTML 的時候反而會被執行的異常狀況(漏洞)。
這樣的行為看似可以符合我們的需求(無腦把 ebmed code 塞進 `dangerouslySetInnerHtml` 他就會動)，但只要 react component re-render 的情況下就會恢復成 CSR 的結果 ( script tags 再次無效化)，結果是還是要特別處理在 useEffect 之中把 script tags 手動 append 上去，然而一但在 useEffect 中加上這段邏輯意味著第一次 browser 從 server 拿到 HTML 的時候又會執行兩次 script …

refactor(draft-renderer/embed-code): optimize embed code UX

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/index.ts
packages/draft-renderer/src/website/mirrormedia/utils/index.ts

由於Adam/mirror-media-next 有需要確認前言或內文是否有內容的需求，原本是寫在 mirror-media-next中 （詳見 https://github.com/mirror-media/Adam/pull/149 ），但後來經文瀚建議，將draft-renderer相關的程式碼都封裝在draft-renderer中，使用draft-renderer的專案則可以直接引用，不需要了解draft-renderer內部的邏輯。

feat(draft-renderer): add utils function to check has content in raw content block

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderer-fn.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/info-box-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx
packages/draft-renderer/src/website/mirrormedia/draft-renderer.tsx
packages/draft-renderer/src/website/mirrormedia/entity-decorator.tsx
packages/draft-renderer/src/website/mirrormedia/entity-decorators/annotation-decorator.tsx
packages/draft-renderer/src/website/mirrormedia/entity-decorators/link-decorator.tsx

1. MirrorMedia底下的元件`<DraftRenderer>`，將新增一參數`contentLayout`。該參數將會影響content block、atomic block所顯示的樣式，如字體、字體大小、顏色、間距等等。
2. 未來將有四種`contentLayout`：`normal`、`wide`、`photography`、`premium`。目前僅新增`normal`與`wide`兩種樣式。
3. 目前透過styled-component的`css`，管理content block、atomic block中不同`contentLayout`所應顯示的樣式為何。
1. 需補上`contentLayout`的type。

feat(draft-renderer/mm): add `wide` layout and change style of certain content and atomic block

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/readr/block-renderers/related-post-block.tsx
packages/draft-renderer/src/website/readr/draft-renderer.tsx
packages/draft-renderer/src/website/readr/types/index.ts
packages/draft-renderer/src/website/readr/utils/index.ts

- 新增 props `insertRecommend`，可傳入「推薦閱讀」文章資料。
- utils 新增 `insertRecommendInContent` 方法，依據「推薦閱讀」文章數量，穿插至原有內文的 blocks/entityMap 中。
- 新增 `types/index.ts`，存放常用 type 設定。 
- `@mirrormedia/lilith-draft-renderer` 版本升至 `1.2.0-alpha.16`。
- 原先是 export `removeEmptyContentBlock` 方法於 READr 的文章頁使用，考量到目前文章頁資料皆會使用到 `removeEmptyContentBlock`，因此修改成讓資料統一於  `draft-renderer/readr` 中處理，文章頁僅需傳原始資料（ ex: postData.content ) 即可，提高易讀性。
- `draft-renderer/readr` 會統一對傳入的 `rawContentBlock` 進行驗證與執行 `removeEmptyContentBlock` ，並依照是否有 `insertRecommend` 參數，決定是否需要執行 `insertRecommendInContent`。

feat(draft-renderer): add `insertRecommend` props & bump version to `1.2.0-alpha.16`

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/readr/utils/index.ts

- 調整「推薦閱讀」穿插內文計算方式：
- 透過 **內文總段落數 /  (相關報導數量+1)** 後四捨五入取整數值，決定穿插間距。
- 當 **相關報導** 數量遠大於 **內文總段落數** 時（四捨五入為 0 時），改為每隔 1 段穿插一篇推薦閱讀，直至內文結束。
- `@mirrormedia/lilith-draft-renderer` 版本升至 `1.2.0-alpha.17`。

fix(draft-renderer/readr): modify recommends insert calculation method

---

packages/core/src/utils/manual-order-relationship.ts
packages/readr/lists/Post.ts
packages/readr/schema.graphql
packages/readr/schema.prisma

KeystoneJS 6 的 relationship 並不會紀錄使用者輸入的順序，K6 的順序是由存入資料庫時所產生的 id 來決定。
但因為編輯台有「紀錄輸入順序」的需求，例如：一篇「文章」（`post`）在輸入「多位作者」（`writers`）時，會希望透過輸入的順序來區分有第一作者、第二作者。
然而，因為 K6 的 relationship field 沒有紀錄「編輯輸入作者時的順序」，所以 query 出來的作者資料，並不會照編輯的設想去排列。
透過 `@readr-media/lilith/core` 提供的 `addManualOrderRelationshipFields` function，在 list object 上加入 `manualOrderOfWriters` 和 `writersInInputOrder` （延續上述範例）兩個 fields；並且針對 `resolveInput` hook 添加邏輯，將 input order 存入 `manualOrderOfWriters`。
而 `authorsInInputOrder` virtual field 則可以提供 GQL schema 和 resolver，將 `manualOrderOfWriters` 和 `writers` 兩個欄位的值排序，依照編輯所輸入的排序回傳。

feat(core): auto add virtual field to return relationship items in input order

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderers/divider-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/info-box-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx
packages/draft-renderer/src/website/mirrormedia/draft-renderer.tsx
packages/draft-renderer/src/website/mirrormedia/shared-style/index.ts

1. 參考`/website/readr`的做法，於mirrormedia中新增一資料夾`/shared-style`，並新增兩個css `defaultMarginBottom`與`defaultMarginTop`，用於設定不同content block、atomic block的css間距。
2. 不預先載入slideshow與imageblock的圖片，以提升載入速度。

feat(draft-renderer): add shared-style for mirrormedia, not preload image

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx

在draft-renderer中，圖片需要在特定的條件下滿版，原本的寫法雖能夠使得圖片滿版，但同時也會造成圖片寬度推擠容器寬度，導致頁面實際寬度變寬。這樣的影響是，在螢幕寬度<640px的情況下，桌機版瀏覽器的的X軸scrollbar會出現並且可被拖曳，但這應該是要避免的。
為了避免這樣的情形發生，改採用了最一開始的寫法，並微調css media-query，使得圖片在滿版的同時，不會推擠容器寬度。

style(draft-renderer): adjust image-block width

---

package.json
packages/editools/keystone.ts
packages/editools/lists/Audio.ts
packages/editools/lists/Conditions.ts
packages/editools/lists/DroppingText.ts
packages/editools/lists/DualSlides.ts
packages/editools/lists/EmbedCode.ts
packages/editools/lists/FeedbackCounter.ts
packages/editools/lists/Field.ts
packages/editools/lists/FieldOption.ts
packages/editools/lists/Form.ts
packages/editools/lists/FormAnswer.ts
packages/editools/lists/Image.ts
packages/editools/lists/IndexItem.ts
packages/editools/lists/InlineIndex.ts
packages/editools/lists/Karaoke.ts
packages/editools/lists/Liveblog.ts
packages/editools/lists/LiveblogItem.ts
packages/editools/lists/QAList.ts
packages/editools/lists/Question.ts
packages/editools/lists/RandomTextSelector.ts
packages/editools/lists/ThreeStoryPoints.ts
packages/editools/lists/Video.ts
packages/editools/lists/VideoPicker.ts
packages/editools/package.json
packages/editools/schema.graphql
packages/editools/schema.prisma

BREAKING CHANGE:
GQL schema is changed due to @keystone-6/core upgrade.
Mainly, fields, such as `image_mode`, `file_mode`, which are generated by `image`, `file` field type are effected.
Related PR:
https://github.com/mirror-media/Lilith/pull/378

refactor(editools)!: upgrade @keystone-6/core to 5.2.0

---

packages/editools/lists/queries/liveblogQuery.ts

Due to this change https://github.com/mirror-media/Lilith/pull/379, GQL schema has changed.
There is no `ref` field anymore. 
Therefore, this patch fixes wrong GQL query.

fix(editools): update liveblogQuery.ts. Remove `ref` field due to gql schema change

---

packages/editools/package.json
packages/editools/yarn.lock

We have two different version `@keystone-ui/modals` installed. When `RichTextEditor`'s custom buttons, such as ColorBox, calls `DrawerProvider`, it will encounters rendering errors. Error log is
```
This component must have a <DrawerProvider/> ancestor in the same React
tree.
```
This patch upgrades `@mirrormedia/lilith-core` to 2.0.0-alpha.5, which upgrades `@keystone-ui/modals` and other `@keystone-ui` related pkgs to the same version on which `@keystone-6/core@5.2.0` depends.
And also remove old `@keystone-6/fields-document` pkg since it is not used and it depends on old `@keystone-ui` pkgs.

fix(editools): rich-text-editor client error bug

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderers/audio-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/embedded-code-block.tsx

1. 調整atomic block renderer `embedded-code-block`樣式
2. 調整atomic block renderer `audio-block`樣式
3. draft-renderer升版至 `1.2.0-alpha.28`

style(draft-renderer/mm): adjust style of audio and embedded code block

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx
yarn.lock

1. 調整draft-renderer中slideshow的程式碼，優化lazy-load觸發條件。
2. 由於lazy-load會導致在特定條件下，圖片會有一閃的狀況發生，所以針對會發生該狀況的圖片，不實作lazy-load（詳細說明註解於[程式碼內](https://github.com/mirror-media/Lilith/pull/431/commits/d3d1f3a373ebbad1696092ad529ea7525eae7d7d#diff-bb63b5da313f4e59069c01475bda6c39bee2277e88e2025e66e7fe1014a44025R204-R215)。）
3. 一閃狀況如影片所示
https://github.com/mirror-media/Lilith/assets/85677992/6458e496-6047-41eb-ac1d-169ce9adab16

refactor(draft-renderer/slideshow): improve user experience when dragging

---

packages/mirrormedia/lists/Post.ts
packages/mirrormedia/lists/Video.ts
packages/mirrormedia/migrations/20230707042603_adjust_relationship_between_videos_and_posts/migration.sql
packages/mirrormedia/schema.prisma

Take the relationship between Post and Tag for reference.
Thank Tsuki for providing the following references:
> https://github.com/mirror-media/Lilith/blob/e458a562af733b8b7a6a4cdf2f12c67383ea1816/packages/mirrormedia/lists/Tag.ts#L26
> https://github.com/mirror-media/Lilith/blob/e458a562af733b8b7a6a4cdf2f12c67383ea1816/packages/mirrormedia/lists/Post.ts#L282

fix(mirrormedia): adjust the relationship between Video and Post

---

packages/mirrormedia/lists/Image.ts
packages/mirrormedia/schema.graphql

仿照 Resized 
新增了一個 ResizedWebp
Image processor 那邊也處理好
同樣尺寸的圖檔會有兩種格式可用
原檔格式及 webP

feat(mirrormedia): add virtual field for resized webp images

---

packages/editools/lists/Theatre.ts
packages/editools/package.json
yarn.lock

- `react-embed-code-generator` 版本升至 `2.4.0-alpha.3`。
- 套用 「READr 版型」至 embedded 樣式。

feat(theatre): add READr `shiftLeft` in embed style

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderer-fn.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/amp/amp-slideshow-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/index.ts

- 新增 amp 用的 slideshow
1. 還沒新增圖解部分，應該是因為 amp 主打載入比較快，蠻多地方都希望直接寫死高度。目前看起來無法達到「隨著文字行數變化高度」。[官方文件](https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/) 的 `Caption with text overlay` 和 `Collapsible Image Captions with amp-bind` 感覺是妥協方法，另外也可參考 [該 codepen 範例](https://codepen.io/TwisterMc/pen/jLOrZL)，留個一點五行讓使用者 scroll。這裡想先進行技術詢問，如果 reviewer 也覺得沒有其他方法，我會再與需求方協調。
2. 希望有滑動效果！目前 [amp-carousel v0.2](https://amp.dev/documentation/components/amp-carousel-v0.2) 已經有了，但目前不確定在該專案中，該如何引入比較妥當？感謝！

feat(draft-renderer): add AmpSlideshowBlockV2

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderer-fn.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/amp/amp-slideshow-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/index.ts
packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx

- 新增 amp fallback 為 default image。
- 統一將 amp component 移至相同功能的 component 內，再用 content layout 選擇要 render 哪個。

refactor(draft-renderer): add fallback of amp-img and move amp component into SlideshowBlockV2

---

packages/editools/lists/DualSlides.ts
packages/editools/package.json
yarn.lock

- 更新 `embed-code-generator` 版本：
- 此版本 `dual-slide` 已修復背景跑位問題。
- 此版本 `timeline` 先降版至穩定版本 `1.1.0-alpha.1`。
- 目前 `dual-slide` 套件已修正為：
- 不再需要透過勾選「READr 版型」checkbox 來調整位移問題，在任何版型都適用（顯示 100vw）
- 因此移除 `shiftLeft` 對於 dual-slide 的樣式設定。
TODO：

fix(editools): update `ecg` version & fix `dual-slide` error 

---

packages/mirrormedia/lists/Post.ts
packages/mirrormedia/schema.graphql

新增virtual field `apiDataTrimmed`，其計算基礎為 field `apiData`的前五段內容。

feat(mirrormedia): add virtual field `apiDataTrimmed` in `Post` list

---

packages/mirrormedia/keystone.ts
packages/mirrormedia/lists/Category.ts
packages/mirrormedia/lists/Post.ts
packages/mirrormedia/lists/Section.ts
packages/mirrormedia/migrations/20230904061617_add_lock_post_fields/migration.sql
packages/mirrormedia/schema.graphql
packages/mirrormedia/schema.prisma

此 PR 包含兩個 commits
第一個 commit 屬於 refactor，與實作 lock 無關。
以下根據第二個 commit，詳細說明 lock 的實作細節。
主要需求：
避免東西被覆蓋。
例如 A, B 都進入同一篇文章，A 辛苦編輯完後，存檔並離開編輯頁面。而 B 的編輯畫面仍是舊的，所以沒有看到 A 寫的東西，然後 B 也寫完存檔離開，把 A 的東西完全覆蓋掉了。
實作上考慮到的使用情境
A 進入編輯 -> B 進入後會看到 `A 正在編輯`，並回給 B read mode
A 進入編輯 -> 編輯完，save changes，鎖釋放
A 進入編輯 -> 編輯完，save changes，鎖釋放，但仍停在原畫面 -> B 進入編輯，B 得到鎖 -> A 在原畫面突然又想編輯 -> A 編輯完按儲存 -> 會得到錯誤警告（因為目前是 B 的編輯時間）
A 進入編輯 -> 突然不想編輯就返回 -> 沒觸發 hooks -> 鎖沒釋放 -> 30 分鐘後由 [mirror-media-cronjobs](https://github.com/mirror-media/mirror-media-cronjobs/commit/cde07c2e98c332792e21cd64a2ec13636db8867e) 去釋放鎖
新增兩個欄位：`lockBy` 及 `lockExpireAt`
並在 `itemViewFunction` 決定要返回 edit or read mode
如果是 edit mode 此時也會賦值給 `lockBy` 及 `lockExpireAt` (目前設定 30 分鐘後，lock 失效)
lock 持有者在 after update operation，更新 `lockBy` 及 `lockExpireAt`。
如果不小心進入別人正在編輯的 …

feat(mirrormedia): implement the lock on Posts

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderers/image-block.tsx
packages/draft-renderer/src/website/mirrormedia/block-renderers/slideshow-block.tsx
yarn.lock

調整draft-renderer中元件image-block與slideshow-block，使其使用2.1.3版本的@readr-media/react-image，並取得資料`resizedWebp`，並將其作為參數`imagesWebp`，傳入`@readr-media/react-image`

feat(draft-renderer): render webp image in image and slideshow block

---

packages/mirrormedia/lists/Post.ts
packages/mirrormedia/lists/views/now-button.tsx
packages/mirrormedia/migrations/20230915003248_add_now_button/migration.sql
packages/mirrormedia/schema.graphql
packages/mirrormedia/schema.prisma
packages/mirrormedia/utils/updateTimestamp.js

- 3.0 k6 CMS 發布日期旁新增「現在時間」點選後發布日期跳為現在時間。
- 學電視直接挖一個 custom field >> k6 使用 ts 導致搬遷過於複雜，未來也不好維護，故先不考慮該方案。
- 使用 virtual field，點擊按鈕後新增欄位 >> 目前可以 migrate 了，只是不會馬上更新，若沒重新整理儲存可能會衝突，覺得不是很好的使用者體驗。
- 新增一個 checkbox 決定是否在儲存時將時間改為現在 >> 不是本來的需求，不過若比較直覺也可採用。
- [Asana 卡片](https://app.asana.com/0/1181156545719626/1205419959719889/f)

refactor(mirrormedia): add virtual field and checkbox for update time

---

packages/mirrormedia/express-mini-apps/preview/app.js

* refactor(mirrormedia): remove `/_next` route
* There is a route collision between CMS and preview next server

refactor(mirrormedia): remove _next route

---

packages/mirrormedia/lists/Post.ts
packages/mirrormedia/lists/views/sorted-relationship/RelationshipSelect.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/InlineCreate.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/InlineEdit.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/index.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/useItemState.tsx
packages/mirrormedia/lists/views/sorted-relationship/index.tsx

CMS relationship 欄位的下拉選單要能從新到舊排序 (照 id)
一開始進入 Post item view 時，用 developer console 去看，發現有 relationship 的欄位會打 graphql 去拿 related list 的資料，預設是 10 筆，而且它的 query 沒有 orderBy，所以預設都是照 id asc 排。
再 trace Keystone relationship 相關的 [code](https://github.com/keystonejs/keystone/blob/main/packages/core/src/fields/types/relationship/views/RelationshipSelect.tsx#L148C3-L160C5)，是這樣沒錯。
參考 Preview button 的方法，它用了一個 custom field view
```
ui: {
// A module path that is resolved from where `keystone start` is run
views: './lists/views/link-button',
......
}
```
目前是直接把 relationship 的 views 直接複製一份到 `packages/mirrormedia/lists/views/sorted-relationship` ([commit 1](https://github.com/mirror-media/Lilith/pull/570/commits/bae4aaae618f3052ae111fc0debdf47d3034d171))，然後補上 orderBy，以及在 `Post.ts` relationship field 指定用這個 …

feat(mirrormedia): add custom view to sort the relationship field

---

packages/mirrormedia/lists/views/sorted-relationship/RelationshipSelect.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/InlineCreate.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/InlineEdit.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/index.tsx
packages/mirrormedia/lists/views/sorted-relationship/index.tsx

此為 [custom relationship field view](https://github.com/mirror-media/Lilith/pull/570) 的後續修正
在複製 keystone 原始碼過來改時，因為有些 eslint error，所以就把程式碼做了一些改動，以便通過 eslint check。
結果發現部分 UI 受影響，按鈕圖片都擠在一起，故將 jsx 加回來，並在有 eslint error 的上方補上
`// eslint-disable-next-line`，作為 workaround。

fix(mirrormedia): add jsx back to fix the custom view

---

packages/mirrormedia/lists/Image.ts
packages/mirrormedia/lists/views/custom-image/Field.tsx
packages/mirrormedia/lists/views/custom-image/index.tsx

- 修改 Post list 內 heroImage field 的 img 大小
- 修改 Image list imageFile 的 img 縮圖大小
比照 [PR570](https://github.com/mirror-media/Lilith/pull/570) 作法，將 [keystone core image field views](https://github.com/keystonejs/keystone/tree/%40keystone-6/core%405.2.0/packages/core/src/fields/types/image/views) 複製一份到 `mirrormedia/lists/views/custom-image` 中，修改對應的 image css。
不管是 Post list內 heroImage 或是 Image list imageFile 的呈現，都會 relate 到 Image list imageFile 所對應到的 views，預設沒有提供的情況下會使用 image field 中的 views ，我們也可以自行帶入 custom views 來呈現我們想要的 img 大小，不過自己寫一份 image field views 的文件並不齊全，較為簡單的作法則是直接複製原本使用的 image field 原本使用的 views，並在顯示端進行修改已達成需求。
複製 source code 的作法代表我們的 views 將會綁定 @keystone-core 5.2.0 的版本，日後若 @keystone-core 針對 field 的格式有調整，本次的改動將需要重新更動 (可能是再複製一次新版的 views 來修改)，在升版時需特別注意。
- feat(mirrormedia): add custom …

refactor(mirrormedia): modify image field view img size

---

packages/draft-renderer/package.json
packages/draft-renderer/src/website/mirrormedia/block-renderers/embedded-code-block.tsx

- 為了處理錯誤訊息 `error  The tag 'iframe' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-iframe'?  https://amp.dev/documentation/components/amp-iframe/` 而將 <iframe> 統一替換成 <amp-iframe>。
- 使用 fb embed 測試時出現了不允許 `allowfullscreen="true"` 在 <amp-iframe> 中，因此也替換成 `allow="fullscreen"`

refactor(mm-next): add convertIframesToAmp

---

packages/core/package.json
packages/draft-editor/package.json
packages/draft-editor/src/draft-js/draft-converter/atomic-block-processor.js
packages/mirrormedia/package.json

Since apiData is now only for App to use, re-structure the apiData from only HTML to two dimension array. First dimension stores rows and the second dimension stores cells with HTML converted from draft.js blocks.
Now App side can use the data structure to custom the style of the table.
```
"content": [
[
{
"html": "<p>R1C1</p>"
},
{
"html": "<p>R1C2</p>"
}
],
[
{
"html": "<p>R2C1</p>"
},
{
"html": "<p>R2C2</p>"
}
],
[
{
"html": "<p></p>"
},
{
"html": "<p></p>"
}
]
],
```

refactor(draft-editor): update table apiData structure

---

packages/mirrormedia/lists/views/sorted-relationship/RelationshipSelect.tsx
packages/mirrormedia/lists/views/sorted-relationship/cards/index.tsx

1. 修改custom-view `sorted-relationship` 的相關元件，使關聯到List `Photo` 的field，可以於下拉式選單顯示圖片樣貌。
使用者希望在選取圖片時，可以於下拉式選單中同步看到圖片的樣子，而非只有圖片名稱。
而依據需求，則具體拆成兩個步驟：
1. 取得圖片的url
2. 將圖片的url顯示在下拉式選單中
就第一步而言，發現在元件`<RelationshipSelect>`中有一個參數[`extraSelection`](https://github.com/mirror-media/Lilith/blob/main/packages/mirrormedia/lists/views/sorted-relationship/RelationshipSelect.tsx#L133)。
而該參數的用途用於[調整gql query 所請求的field](https://github.com/mirror-media/Lilith/blob/main/packages/mirrormedia/lists/views/sorted-relationship/RelationshipSelect.tsx#L299)，也就是可以額外抓取特定欄位的資料。
因此，本次改動使用該參數來抓取 List `Photos`的 Field [`imageFile`](https://github.com/mirror-media/Lilith/blob/main/packages/mirrormedia/lists/views/sorted-relationship/RelationshipSelect.tsx#L299)。另外有加上條件判斷，只有特定的List 才會傳入該參數，避免造成非預期的錯誤。
而就第二步而言，由於keystone使用了第三方套件 …

feat(mm): show image url when relation to List `Photos`

---

packages/mirrormedia/lists/External.ts
packages/mirrormedia/lists/Group.ts
packages/mirrormedia/lists/Post.ts
packages/mirrormedia/lists/index.ts
packages/mirrormedia/migrations/20240410062250_add_group_list/migration.sql
packages/mirrormedia/schema.graphql
packages/mirrormedia/schema.prisma

新增Group list，用來記錄演算法分群的結果，裡面主要有幾個欄位
1. keyword: 演算法計算某一時間內的焦點關鍵詞
2. posts: 與該關鍵詞最為相關的近期內部文章
3. externals: 與該關鍵詞最為相關的近期外部文章
hook函式僅針對keyword為空的情形進行檢查。另外，調整外部文章相關文章功能為連結週刊內部文章。

feat(mm): add group list and modify the relationship of external and post

---

packages/mirrormedia/lists/Post.ts
packages/mirrormedia/lists/Tag.ts
packages/mirrormedia/migrations/20240415022025_add_post_tags_algo/migration.sql
packages/mirrormedia/schema.graphql
packages/mirrormedia/schema.prisma

在這個PR裡面主要做兩件事情，分別如下
1. 修正post的updatedAt：原先在建立文章時不會自動寫入updatedAt的欄位導致會有空值產生，這邊修改hook使文章建立時寫入updatedAt欄位為現在時間。
2. 新增演算法標籤tags_algo：為了與人工標籤分開，在Post新增演算法標籤的欄位。
updatedAt的相關issue為Asana的RSS邏輯調整任務，主要問題是若將篩選標準改為更新時間的情況下，直接建立狀態為已發佈的文章更新時間為空值，會導致排序錯誤。
[RSS抓取時間邏輯調整](https://app.asana.com/0/1206837560996882/1206848017516544/f)

feat(mm): add post tags_algo and modify updatedAt in Post list

---

packages/mirrormedia/lists/Post.ts
packages/mirrormedia/schema.graphql

由於演算法計算的欄位不應該一般使用者看見及使用，這邊將在Posts list裡面與算法相關的欄位隱藏起來，並設定isFilterable: false。
由於該次沒有schema變更，所以沒有migration檔案產生。

feat(mm): hide algorithm auto-calculated fields in posts

---

packages/mesh/lists/index.ts
packages/mesh/lists/policy.ts
packages/mesh/lists/transaction.ts
packages/mesh/migrations/20240710083124_add_policy_transaction_list/migration.sql
packages/mesh/migrations/20240711025115_fix_transaction_member_relation/migration.sql
packages/mesh/schema.graphql
packages/mesh/schema.prisma

新增Policy(政策)和Transaction(交易紀錄)的Lists，用來管理儲值與付費解鎖相關資料。
在Policy(政策)制定不同媒體的文章收費方式，並藉由設定Unlock single控制該政策負責的是"單一文章解鎖"或"解鎖該媒體所有文章"，並設定Duration設定解鎖後的有效期限。
Transaction(交易紀錄)則是使用者在Client-side藉由錢包完成支付後需要寫入到CMS的資料，在後台我們會參考Transaction綁定的Policy得知為儲值或解鎖文章，我們會拿TID至鏈上進行交易查詢比對金額是否符合，若符合的話將status設定為成功。
另外，使用者仍在有效期限內的Transaction紀錄後續會包在JWT裡面作為AccessToken的驗證資訊。
此次更動僅支援加密貨幣的支付方式，若需要支援一般支付方式(Linepay, Googlepay......)需額外再設計。
詳細欄位說明請參考Dropbox文件如下
https://paper.dropbox.com/doc/CMSMesh--CSrQ8xSjjbTdeCyjVbAudO_fAg-bEsabOAeV6VzR52lYfyHm

feat(mesh): add policy and transaction lists

---

packages/mirrordaily/lists/EditorChoice.ts
packages/mirrordaily/lists/Game.ts
packages/mirrordaily/migrations/20240724161735_add&remove_game&editorchoice_list/migration.sql
packages/mirrordaily/schema.graphql
packages/mirrordaily/schema.prisma

1. 補上migration file 上沒有在欄位加上quote 的 bug 以及 description 加上s
2. Improve EditorChoice 的首圖欄位使用者體驗

fix(mirrordaily): add missing 'quote' on migrations file and 's' in description

---

packages/mesh/lists/member.ts
packages/mesh/lists/transaction.ts
packages/mesh/schema.graphql
packages/mesh/schema.prisma

補上list當中member到transaction的關聯，無資料庫schema更動故無migration檔案。

feat(mesh): add relationship from member to transaction

---

packages/mesh/lists/exchange.ts
packages/mesh/lists/sponsorship.ts
packages/mesh/lists/transaction.ts
packages/mesh/migrations/20241220023445_add_status_processing_transaction/migration.sql
packages/mesh/schema.graphql
packages/mesh/schema.prisma

因應接下來交易驗證的更版，此次PR針對交易相關的欄位新增狀態(status): Processing。
後續相關交易驗證的更版流程，請參考以下文件：
https://paper.dropbox.com/doc/Payment--Cc1iH_~Oes6Vr6cXVhd2xWVKAQ-nqZHuR0SkiPpqrXwdpXZH

feat(mesh): add new status processing to transaction related lists

---

packages/mesh/lists/exchange.ts
packages/mesh/lists/sponsorship.ts
packages/mesh/lists/transaction.ts

因應交易驗證的流程更動，將交易相關的lists的TID(區塊鏈交易編號)改為非必須，
使交易開始前能夠預先建立交易訂單。

feat(mesh): modify tid of transaction related list isRequired to false

---

packages/mesh/lists/story.ts
packages/mesh/lists/tag.ts
packages/mesh/migrations/20250108070019_modify_story_tag_relationship/migration.sql
packages/mesh/schema.prisma

修正story和tag兩個list之間的關係，使可從tag反相查看到使用該tag的文章。
(原本的實作當story關聯到tag後，tag內部的story並沒有記錄到使用該story)

feat(mesh): modify story tag relationship

---

packages/mirrormedia/keystone.ts
packages/mirrormedia/lists/Announcement.ts
packages/mirrormedia/lists/AnnouncementScope.ts
packages/mirrormedia/lists/index.ts
packages/mirrormedia/migrations/20250115031008_add_annoucement_list/migration.sql
packages/mirrormedia/schema.graphql
packages/mirrormedia/schema.prisma

* 增加 Announcement 和 AnnouncementScope list，作為公告使用 ([參考](https://paper.dropbox.com/doc/--CecP_cSQcIbFfDIKiQdDQGkKAg-LtpvUSQx42SAOzCX9Dx00#:h2=CMS-%E5%A2%9E%E5%8A%A0-Announcement-%E5%92%8C-Announce))
* AnnouncementScope 預設加入 `all` 和 `papermag` 的資料，並做碰撞處理 ([參考](https://docs.postgresql.tw/reference/sql-commands/insert#on-conflict-clause))
---
- https://app.asana.com/0/0/1209097125214556

feat(mirrormedia): add announcement lists

---

packages/mesh/lists/member.ts
packages/mesh/migrations/20250124061551_add_member_balance/migration.sql
packages/mesh/schema.graphql
packages/mesh/schema.prisma

為了避免在產生財報時需在鏈上查詢大量的餘額資料，
在此次更新中為member新增balance欄位，該欄位會在空投與交易行為完成後將用戶更新後的餘額寫入，
使在進行財報計算時便可以直接從GQL快速拉出餘額資料進行統計。

feat(mesh): add balance column to member list

---

packages/mesh/lists/comment.ts
packages/mesh/lists/pick.ts
packages/mesh/lists/podcast.ts
packages/mesh/lists/story.ts
packages/mesh/migrations/20250208062324_modify_story_and_podcast_list_the_revision_is_to_separate_podcast_text_document_and_src/migration.sql
packages/mesh/migrations/20250208073215_modify_story_and_podcast_list_the_revision_is_to_separate_podcast_text_document_and_src/migration.sql
packages/mesh/schema.graphql
packages/mesh/schema.prisma

此份PR主要是將Podcast 以及 Story list 進行些微修改，將Podcast的來源與偏向document的資料拆開
1. document相關的儲存在story list
2. url 來源以及媒體 source 儲存在 podcast list 並且相關聯story list
3. story list 新增判斷type欄位

feat: modify story and podcast list, the revision is to separate podcast text document and src

---

packages/mesh/lists/index.ts
packages/mesh/lists/revenue.ts
packages/mesh/lists/statement.ts
packages/mesh/migrations/20250212032057_add_revenue_and_statement_list/migration.sql
packages/mesh/schema.graphql
packages/mesh/schema.prisma

新增收益(revenue)與報表(statement)的list，兩者分別用途如下
1. revenue: 在每個月計算廣告分潤(from gam)與基金池分潤(from adsense)時，將資料寫入revenue
2. statement: 在產出月報(month)/季報(qualter)/半年報(semi_annual)時，將檔案來源與相關資料寫入statement
實際運作情形如下：
在每個月計算月報表時，將各媒體廣告分潤與基金池分潤一併寫入revenue list當中供後續查詢；在產製個報表時，會將資訊寫入statement list，需注意季報會需要該媒體前幾個月的廣告收益，此部分會從revenue list取得。
另需注意，在statement中的報表檔案連結，若非具權限的Google帳戶時，會需要Signed cookie才可以進行讀檔，此部分會依照以不同的媒體切割權限。

feat(mesh): add revenue and statement list

---

packages/mirrordaily/lists/Topic.ts
packages/mirrordaily/migrations/20250212060230_add_api_data_brief_field_to_topic/migration.sql
packages/mirrordaily/schema.graphql
packages/mirrordaily/schema.prisma

* 隱藏以下未被使用的欄位：
* 分區
* 置頂
* 專題樣式
* javascript
* DFP code
* mobile DFP code
* 刪除型態欄位中，Timeline 與 Portrait Wall 選項
* 調整欄位順序，使用者在設定「標頭樣式」後，就近可以設定對應的「首圖」、「首圖影片」或「slideshow 圖片」資訊

refactor(daily): update topic list

---

packages/mesh/lists/member.ts
packages/mesh/migrations/20250224024903_add_language_field_to_member/migration.sql
packages/mesh/schema.graphql
packages/mesh/schema.prisma

將語系的欄位新增至member的list，預設使用zh-TW，並提供其他主流語言的對照碼。
現提供以下語系，並因應地區性差異做區別:
{label: "中文-台灣", value: "zh_TW"},
{label: "中文-中國", value: "zh_CN"},
{label: "英文-美國", value: "en_US"},
{label: "英文-英國", value: "en_GB"},
{label: "日文-日本", value: "ja_JP"},
{label: "法文-法國", value: "fr_FR"},
{label: "德文-德國", value: "de_DE"},
語系對照表請參考以下網站
https://hoohoo.top/blog/national-language-code-table-zh-tw-zh-cn-en-us-json-format/

feat(mesh): add language field into member list

---

packages/mirrordaily/environment-variables.ts
packages/mirrordaily/keystone.ts
packages/mirrordaily/lists/Category.ts
packages/mirrordaily/lists/EditorChoice.ts
packages/mirrordaily/lists/Event.ts
packages/mirrordaily/lists/External.ts
packages/mirrordaily/lists/Game.ts
packages/mirrordaily/lists/Group.ts
packages/mirrordaily/lists/Post.ts
packages/mirrordaily/lists/Section.ts
packages/mirrordaily/lists/Topic.ts
packages/mirrordaily/lists/Video.ts
packages/mirrordaily/type.ts

* Topic List 增加 filter 處理
* Section List 增加 filter 處理
* Category List 增加 filter 處理
* 增加 ACL, State, UserRole 三個共用的 enum
* 增加 Session 共用的 type
* 請 @nickchen111  確認 Topic, Section 和 Category 加上 filter 後，後端相關服務 (如：cronjobs) ，在呼叫 GQL API 的輸出結果是否異常
* Topic 在 GQL API 僅輸出 state 為 `published` 的紀錄
* Section 在 GQL API 僅輸出 state 為 `active` 的紀錄
* Category 在 GQL API 僅輸出 state 為 `active`  的紀錄

feat(daily): add filter to Topic, Section and Category list

---

packages/mirrordaily/run.sh

* 簡化 http2 proxy 的啟動邏輯，改為參考的是 `REVERSE_PROXY_PORT` 是否設定，而非 `IS_UI_DISABLED`。原本，GQL API 不啟動 Adamin UI，且 GQL API 不使用 http2 proxy，所以使用 `IS_UI_DISABLED` 作為參考，但在 daily 的情境下，因為 GQL API 需要啟動 http2 proxy，與原先 `IS_UI_DISABLED` 的參考邏輯衝突，為了簡化邏輯，改用 `REVERSE_PROXY_PORT` 作為參考

refactor(daily): http2 proxy activation logic

---

packages/mirrordaily/admin/pages/custom-post-creation/index.tsx
packages/mirrordaily/lists/Post.ts
packages/mirrordaily/lists/views/default-author-relationship/RelationshipSelect.tsx
packages/mirrordaily/lists/views/default-author-relationship/cards/InlineCreate.tsx
packages/mirrordaily/lists/views/default-author-relationship/cards/InlineEdit.tsx
packages/mirrordaily/lists/views/default-author-relationship/cards/index.tsx
packages/mirrordaily/lists/views/default-author-relationship/cards/useItemState.tsx
packages/mirrordaily/lists/views/default-author-relationship/index.tsx
packages/mirrordaily/lists/views/default-section-relationship/RelationshipSelect.tsx
packages/mirrordaily/lists/views/default-section-relationship/cards/InlineCreate.tsx
packages/mirrordaily/lists/views/default-section-relationship/cards/InlineEdit.tsx
packages/mirrordaily/lists/views/default-section-relationship/cards/index.tsx
packages/mirrordaily/lists/views/default-section-relationship/cards/useItemState.tsx
packages/mirrordaily/lists/views/default-section-relationship/index.tsx

* 增加 DefaultSectionRelationship 和 DefaultAuthorRelationship view，使文章建立時，在不同的建立 UI  (`/custom-post-creation` 和 `/posts/create`)皆可自動帶入數值
* 因為前者已經自動帶入數值了，移除在 `/custom-post-creation` 帶入數值的行為

refactor(daily): add CustomRelationship views and update CustomPostCreation UI

---

packages/mirrordaily/lists/Post.ts

* 修正與 Post list lockBy 相關的錯誤
* 由於定期解 lock 的 cronjob 似乎尚未部屬，所以在上 lock 與解 lock 處理上，皆用 CMS 自己的方式解決。
* 寫入 lock 資訊時，如果使用者角色是 Editor，且並非文章建立者，則會被擋下
* lock 過期時，可以讓渡 lock 給角色是 Moderator 的使用者，或是文章建立者
* 驗證送出的修改訊息時，會驗證 lock 是否過期

fix(daily): lockBy related errors

---

packages/mirrordaily/lists/External.ts
packages/mirrordaily/lists/Tag.ts
packages/mirrordaily/lists/Topic.ts

Add filtering logic consistent with the one used in posts. Apply the same condition to filter out draft posts from tags, topics, and external references.

feat: add filtering condition to topic, tag, external

---

packages/mirrormedia/lists/Post.ts
packages/mirrormedia/lists/views/related-posts-order/index.tsx
packages/mirrormedia/schema.graphql
packages/mirrormedia/schema.prisma

- 新增使用者操作「相關文章」為單向關聯 `related_posts`
- 新增使用者設定「相關文章」的順序 `related_posts_order`
- 同步單向關聯 `related_posts` 和 雙向關聯 `relateds` (待PM驗收後會隱藏 `relateds`)
- 因 `relationship()` 沒有 order control, 因此須由 client-side fetch data 後做 `related_posts/relateds` 和 `related_posts_order` 處理顯示排序邏輯
---
- https://app.asana.com/0/0/1209933674266086
- https://app.asana.com/0/0/1209945127522883

feat(mirrormedia): related posts connections
